name: TedAlger
favicon: null
layout_spectrum: 0.9492
typography_spectrum: 0.26468
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d1721'
    - '#8cc5f0'
    - '#354857'
    - '#d1edf8'
    - '#687436'
  brandStrength: 0.6583744136150926
  lightness: 0.4879852272570133
  saturation: 0.3897416971158236
  rhythmicContrast: 0.14628252270631492
purpose: []
